---
deployment:
  tasks:
    - current_path=`pwd`
    - if [ $current_path == "/home/balw8356/repositories/our-wedding-hyrba" ]; then export DEPLOYPATH=/home/balw8356/; fi;
    - /bin/cp -R * $DEPLOYPATH/our-wedding-hyrba/
    - /bin/cp -r $current_path/public/template $DEPLOYPATH/public_html/
    - /bin/cp -r $current_path/public/template_welcome $DEPLOYPATH/public_html/
    - /bin/cp -r $current_path/public/images $DEPLOYPATH/public_html/
    - /bin/cp -r $current_path/public/videos $DEPLOYPATH/home/public_html/
    - /bin/cp -r $current_path/public/audios $DEPLOYPATH/home/public_html/
